In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/SKPC.csv")
df

        Data  Open  High    Low  Close  Volume
0  2026-2-20  17.0  17.3  16.50  17.29    3.67
1  2026-2-21  18.0  18.3  17.50  18.29    4.84
2  2026-2-25  17.1  17.2  16.91  17.10    3.84

In [4]:
df.dtypes

Data          str
Open      float64
High      float64
Low       float64
Close     float64
Volume    float64
dtype: object

In [5]:
df["Data"] = pd.to_datetime(df["Data"])
df.dtypes

Data      datetime64[us]
Open             float64
High             float64
Low              float64
Close            float64
Volume           float64
dtype: object

In [6]:
df

        Data  Open  High    Low  Close  Volume
0 2026-02-20  17.0  17.3  16.50  17.29    3.67
1 2026-02-21  18.0  18.3  17.50  18.29    4.84
2 2026-02-25  17.1  17.2  16.91  17.10    3.84

In [9]:
df.set_index("Data", inplace=True)
df

            Open  High    Low  Close  Volume
Data
2026-02-20  17.0  17.3  16.50  17.29    3.67
2026-02-21  18.0  18.3  17.50  18.29    4.84
2026-02-25  17.1  17.2  16.91  17.10    3.84

In [11]:
df

            Open  High    Low  Close  Volume
Data
2026-02-20  17.0  17.3  16.50  17.29    3.67
2026-02-21  18.0  18.3  17.50  18.29    4.84
2026-02-25  17.1  17.2  16.91  17.10    3.84

In [12]:
df["Daily_Return"] = df["Close"].pct_change()
df

            Open  High    Low  Close  Volume  Daily_Return
Data
2026-02-20  17.0  17.3  16.50  17.29    3.67           NaN
2026-02-21  18.0  18.3  17.50  18.29    4.84      0.057837
2026-02-25  17.1  17.2  16.91  17.10    3.84     -0.065063

In [13]:
df.isna()

             Open   High    Low  Close  Volume  Daily_Return
Data
2026-02-20  False  False  False  False   False          True
2026-02-21  False  False  False  False   False         False
2026-02-25  False  False  False  False   False         False

In [14]:
df["MA_2"] = df["Close"].rolling(window=2).mean()
df

            Open  High    Low  Close  Volume  Daily_Return    MA_2
Data
2026-02-20  17.0  17.3  16.50  17.29    3.67           NaN     NaN
2026-02-21  18.0  18.3  17.50  18.29    4.84      0.057837  17.790
2026-02-25  17.1  17.2  16.91  17.10    3.84     -0.065063  17.695